baseURL = "https://techinfo.newmsx.nl/"
languageCode = "en-us"
title = "NewMSX MSX tech info pages"
theme = "techdoc"
canonifyURLs = true
copyright = 'All content is under the  CC BY-NC-SA 4.0.'
enableGitInfo = true
enableRobotsTXT = true

[params]
  filebaseurl = "https://files.techinfo.newmsx.nl"
